### ISSUE TITLE
I cannt find data “"data/vectors.6B.200d.txt"”

### ISSUE THREAD

**Issue by Oliveche** [BarakOshri/TextualReconstructor#1]
Hello，
I cannt find data “"data/vectors.6B.200d.txt"” 。Can you give me ？ Thank you very much！
My email is che.lei@163.com .
Good Luck!

**Comment by nishithbsk** [comment]
Hi, you should be able to download the word vectors from this link: http://nlp.stanford.edu/data/glove.6B.zip
